### ISSUE TITLE
png support

### ISSUE THREAD

**Issue by victornor** [Wilnath/asetroot#6]
This library is amazing and even works with multiple of the compositors i've tried!
But is there any limitation causing it to only support .gif frames?
Would it somehow be possible to somehow support other file formats?

Another question: Is there a limit to the amount of frames?

Thanks for this great project!

**Comment by Wilnath** [comment]
Hey! Thanks for checking out asetroot!

I checked it out on my own machine, and it turns out imlib (the library I use for this project) accepts .png images just fine. I probably just said to use .gif cause that was the only one I've tried when writing the readme. Whoops.

To use png, you're gonna have to specify the format to be "%05d.png", so something like
`$ asetroot folder_with_pngs/ -f %05d.png`

As for a frame limit, the program itself doesn't have a built in limit _buuuuuuuuuuut_ each frame does eat quite a bit of memory so do keep an eye on that.

Let me know if this does the job for you!

**Comment by victornor** [comment]
Hey, that's great, I'll give it a try!
I have plenty of memory and i'm happy to sacrifice for the rice 😀

**Comment by victornor** [comment]
This didn't seem to work, so i setup a debug environment-
Apparently ffmpeg output was starting at 00001 and not 00000 haha.

Everything is working as expected, but i'm having a hard time understanding this memory usage.
Do you mind explaining this, if you know what's going on?

I would expect the memory usage to be that of all the files combined. So if i have 1gb worth of files, the memory usage would be 1gb?
But this is not the case, as it's using many times the size of the files for some reason.
And once loading is done, memory usage drops to 0, how can this be?

Thanks!

**Comment by victornor** [comment]
I created a PR to completely remove all memory usage associated with loading the images.
I literally have 0 C/C++ experience, so i don't know if this might have any consequences, but i have a hard time seeing how that could be.
CPU and memory is literally almost 0.
